# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Water Protector Anti-Repression Crew"
tagline:          "The Frontlines are Everywhere"
description:      "From pipelines to courtrooms to prisons, building strong movement defense."
url:              https://antirepressioncrew.org
baseurl:          /

paginate:         20

# Custom vars
version:          1.0.1
